-- MySQL Script generated by MySQL Workbench
-- Fri Jun 16 17:51:30 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL COMMENT '账户名',
  `nickname` VARCHAR(45) NULL COMMENT '昵称',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `prefix` INT(2) NULL,
  `phone` BIGINT(11) NULL,
  `created_at` INT NULL COMMENT '创建时间',
  `updated_at` INT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(250) NULL COMMENT '资源标题',
  `img_url` VARCHAR(1000) NULL COMMENT '图片地址',
  `created_at` INT NULL COMMENT '创建时间',
  `updated_at` INT NULL COMMENT '更新时间',
  `status` INT NULL COMMENT '资源状态',
  PRIMARY KEY (`id`),
  INDEX `fk_resources_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_resources_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT '用户id',
  `resources_id` INT NOT NULL COMMENT '资源id',
  `created_at` INT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_user_likes_user1_idx` (`user_id` ASC),
  INDEX `fk_user_likes_resources1_idx` (`resources_id` ASC),
  CONSTRAINT `fk_user_likes_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_likes_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT '用户id',
  `resources_id` INT NOT NULL COMMENT '资源id',
  `content` VARCHAR(500) NULL COMMENT '评论内容',
  `created_at` INT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `fk_user_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_user_comment_resources1_idx` (`resources_id` ASC),
  CONSTRAINT `fk_user_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_comment_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
